defaults:
  - _self_
  - env: pusht
  - policy: diffusion

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}_${env.name}_${policy.name}_${hydra.job.name}
  job:
    name: default

seed: 1337
# batch size for TorchRL SerialEnv. Each underlying env will get the seed = seed + env_index
# NOTE: batch size of 1 is not yet supported! This is just a placeholder for future support. See
# `lerobot.common.envs.factory.make_env` for more information.
rollout_batch_size: 1
device: cuda  # cpu
prefetch: 4
eval_freq: ???
save_freq: ???
eval_episodes: ???
save_video: false
save_model: true
save_buffer: false
train_steps: ???
fps: ???

offline_prioritized_sampler: true

n_action_steps: ???
env: ???

policy: ???

wandb:
  enable: false
  # Set to true to disable saving an artifact despite save_model == True
  disable_artifact: false
  project: lerobot
  notes: ""
