defaults:
  - _self_
  - env: pusht
  - policy: diffusion

hydra:
  run:
    dir: outputs/train/${now:%Y-%m-%d}/${now:%H-%M-%S}_${env.name}_${policy.name}_${hydra.job.name}
  job:
    name: default

device: cuda  # cpu
seed: ???
dataset_repo_id: lerobot/pusht

training:
  offline_steps: ???
  online_steps: ???
  online_steps_between_rollouts: ???
  online_sampling_ratio: 0.5
  eval_freq: ???
  save_freq: ???
  log_freq: 250
  save_model: false

eval:
  n_episodes: 1
  # TODO(alexander-soare): Right now this does not work. Reinstate this.
  batch_size: 1

wandb:
  enable: true
  # Set to true to disable saving an artifact despite save_model == True
  disable_artifact: false
  project: lerobot
  notes: ""
