defaults:
  - _self_
  - env: pusht
  - policy: diffusion

hydra:
  run:
    dir: outputs/train/${now:%Y-%m-%d}/${now:%H-%M-%S}_${env.name}_${policy.name}_${hydra.job.name}
  job:
    name: default

seed: 1337
# batch size for TorchRL SerialEnv. Each underlying env will get the seed = seed + env_index
# NOTE: only diffusion policy supports rollout_batch_size > 1
rollout_batch_size: 1
device: cuda  # cpu
prefetch: 4
eval_freq: ???
save_freq: ???
eval_episodes: ???
save_video: false
save_model: false
save_buffer: false
train_steps: ???
fps: ???

offline_prioritized_sampler: true

dataset:
  repo_id: ???

n_action_steps: ???
n_obs_steps: ???
env: ???

policy: ???

wandb:
  enable: true
  # Set to true to disable saving an artifact despite save_model == True
  disable_artifact: false
  project: lerobot
  notes: ""
