# @package _global_

eval_episodes: 50
eval_freq: 7500
save_freq: 75000
log_freq: 250
# TODO: same as simxarm, need to adjust
offline_steps: 25000
online_steps: 25000

fps: 50

dataset_id: aloha_sim_insertion_human

env:
  name: aloha
  task: insertion
  from_pixels: True
  pixels_only: False
  image_size: [3, 480, 640]
  action_repeat: 1
  episode_length: 400
  fps: ${fps}

policy:
  state_dim: 14
  action_dim: 14
