# @package _global_

eval_episodes: 20
eval_freq: 1000
save_freq: 10000
log_freq: 50
offline_steps: 25000
online_steps: 25000

fps: 15

dataset_id: xarm_lift_medium

env:
  name: xarm
  task: XarmLift-v0
  from_pixels: True
  pixels_only: False
  image_size: 84
  # action_repeat: 2  # we can remove if policy has n_action_steps=2
  episode_length: 25
  fps: ${fps}

policy:
  state_dim: 4
  action_dim: 4
