name: Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      DATA_DIR: tests/data
      MUJOCO_GL: egl
    steps:
      - name: Add SSH key for installing envs
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: ${{ (github.ref == 'refs/heads/main') && 'pip' || '' }}
          cache-dependency-path: pyproject.toml

      - name: Install EGL
        run: sudo apt-get update && sudo apt-get install -y libegl1-mesa-dev

      - name: Install pip dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[test, aloha, xarm, pusht]"

      - name: Test with pytest
        run: pytest -v --cov=./lerobot tests

      - name: Test end-to-end
        run: make test-end-to-end
